module.exports = function (sequelize, DataTypes) {
  return sequelize.define('servant', {
    id: { type: DataTypes.BIGINT(11), primaryKey: true, autoIncrement: true, unique: true },
    cname: { type: DataTypes.TEXT, defaultValue: '' },
    jname: { type: DataTypes.TEXT, defaultValue: '' },
    ename: { type: DataTypes.TEXT, defaultValue: '' },
    star: { type: DataTypes.BIGINT(11) },
    class: { type: DataTypes.TEXT, defaultValue: '' },
    avatar: { type: DataTypes.TEXT, defaultValue: '' },
    pic1: { type: DataTypes.TEXT, defaultValue: '' },
    pic2: { type: DataTypes.TEXT, defaultValue: '' },
    pic3: { type: DataTypes.TEXT, defaultValue: '' },
    pic4: { type: DataTypes.TEXT, defaultValue: '' },
    baseHP: { type: DataTypes.BIGINT(11) },
    baseATK: { type: DataTypes.BIGINT(11) },
    max0HP: { type: DataTypes.BIGINT(11) },
    max0ATK: { type: DataTypes.BIGINT(11) },
    max1HP: { type: DataTypes.BIGINT(11) },
    max1ATK: { type: DataTypes.BIGINT(11) },
    max2HP: { type: DataTypes.BIGINT(11) },
    max2ATK: { type: DataTypes.BIGINT(11) },
    max3HP: { type: DataTypes.BIGINT(11) },
    max3ATK: { type: DataTypes.BIGINT(11) },
    max4HP: { type: DataTypes.BIGINT(11) },
    max4ATK: { type: DataTypes.BIGINT(11) },
    lv90HP: { type: DataTypes.BIGINT(11) },
    lv90ATK: { type: DataTypes.BIGINT(11) },
    lv100HP: { type: DataTypes.BIGINT(11) },
    lv100ATK: { type: DataTypes.BIGINT(11) },
    cost: { type: DataTypes.BIGINT(11) },
    illust: { type: DataTypes.TEXT, defaultValue: '' },
    cv: { type: DataTypes.TEXT, defaultValue: '' },
    gluten: { type: DataTypes.TEXT, defaultValue: '' },
    durable: { type: DataTypes.TEXT, defaultValue: '' },
    agile: { type: DataTypes.TEXT, defaultValue: '' },
    magic: { type: DataTypes.TEXT, defaultValue: '' },
    lucky: { type: DataTypes.TEXT, defaultValue: '' },
    treasureRank: { type: DataTypes.TEXT, defaultValue: '' },
    cardA: { type: DataTypes.BIGINT(11) },
    cardB: { type: DataTypes.BIGINT(11) },
    cardQ: { type: DataTypes.BIGINT(11) },
    intro1: { type: DataTypes.TEXT, defaultValue: '' },
    intro2: { type: DataTypes.TEXT, defaultValue: '' },
    intro3: { type: DataTypes.TEXT, defaultValue: '' },
    intro4: { type: DataTypes.TEXT, defaultValue: '' },
    intro5: { type: DataTypes.TEXT, defaultValue: '' },
    intro6: { type: DataTypes.TEXT, defaultValue: '' },
    intro7: { type: DataTypes.TEXT, defaultValue: '' },
    property: { type: DataTypes.TEXT, defaultValue: '' },
    camp: { type: DataTypes.TEXT, defaultValue: '' },
    crit: { type: DataTypes.TEXT, defaultValue: '' },
    death: { type: DataTypes.TEXT, defaultValue: '' },
    critPr: { type: DataTypes.TEXT, defaultValue: '' },
    initiativeNp: { type: DataTypes.TEXT, defaultValue: '' },
    passiveRate: { type: DataTypes.TEXT, defaultValue: '' },
    hitA: { type: DataTypes.BIGINT(11) },
    hitB: { type: DataTypes.BIGINT(11) },
    hitQ: { type: DataTypes.BIGINT(11) },
    hitEX: { type: DataTypes.BIGINT(11) },
    height: { type: DataTypes.BIGINT(11) },
    weight: { type: DataTypes.BIGINT(11) },
    origin: { type: DataTypes.TEXT, defaultValue: '' },
    region: { type: DataTypes.TEXT, defaultValue: '' },
    nature: { type: DataTypes.TEXT, defaultValue: '' },
    gender: { type: DataTypes.TEXT, defaultValue: '' },
    circle: { type: DataTypes.TEXT, defaultValue: '' },
    tdPointQ: { type: DataTypes.TEXT, defaultValue: '' },
    tdPointA: { type: DataTypes.TEXT, defaultValue: '' },
    tdPointB: { type: DataTypes.TEXT, defaultValue: '' },
    tdPointEX: { type: DataTypes.TEXT, defaultValue: '' },
    whereform: { type: DataTypes.TEXT, defaultValue: '' },
  }, {
    timestamp: true,
    underscored: true,
    tableName: 'servant',
    charset: 'utf8',
    collate: 'utf8_general_ci'
  })
}
